# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('home', '0002_auto_20151229_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTopStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('sector_name', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Sector Name - Headline')),
                ('top_stories_content', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Main content field for top stories')),
                ('link_caption', models.CharField(help_text='Text for clickable links to specific sector', max_length=250)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='displayTitle',
            new_name='display_title',
        ),
        migrations.AddField(
            model_name='homepagetopstories',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_stories', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='homepagetopstories',
            name='url',
            field=models.ForeignKey(blank=True, help_text='Internal path to specific sector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
    ]
