# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160125_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='display_title',
        ),
    ]
