# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viz_type', models.CharField(choices=[(b'pie', b'Pie Chart'), (b'bar', b'Bar Chart'), (b'link', b'Link'), (b'list', b'List'), (b'map', b'Map'), (b'number', b'Big Number')], default=b'', help_text=b'Select the type of data vizulation for this Core Measure', max_length=1, null=True)),
                ('prime_label', models.CharField(blank=True, default=b'', help_text=b'This will be primary label/text for the data vizulation', max_length=255, null=True)),
                ('year', models.CharField(blank=True, default=b'', help_text=b'Input the year/date range for the associated data vizulation', max_length=255, null=True)),
                ('data_values', models.CharField(blank=True, default=b'', help_text=b'Enter your values here. If there is more than one value present, separate them by a semicolon', max_length=255, null=True)),
                ('data_labels', models.CharField(blank=True, default=b'', help_text=b'Enter your labels here. If there is more than one label present, separate them by a semicolon', max_length=255, null=True)),
                ('x_axis_label', models.CharField(blank=True, default=b'', help_text=b'Enter your x-axis label here', max_length=255, null=True)),
                ('y_axis_label', models.CharField(blank=True, default=b'', help_text=b'Enter your y-axis label here', max_length=255, null=True)),
            ],
        ),
    ]
