# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_mainfootertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryFooterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text="Header text to display above text. Ex. 'Welcome'", max_length=100)),
                ('content', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
        ),
    ]
