# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0008_auto_20160413_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremeasurerelateddata',
            name='source',
            field=models.TextField(blank=True, default=b'', help_text=b'Source text for data visualization', null=True),
        ),
        migrations.AlterField(
            model_name='coremeasurerelateddata',
            name='data_labels',
            field=models.CharField(blank=True, default=b'', help_text=b'Enter your labels here. If there is more than one label present, separate them by a semicolon', max_length=255, null=True, verbose_name=b'Data Labels'),
        ),
        migrations.AlterField(
            model_name='coremeasurerelateddata',
            name='data_values',
            field=models.CharField(blank=True, default=b'', help_text=b'Enter your values here. If there is more than one value present, separate them by a semicolon', max_length=255, null=True, verbose_name=b'Data'),
        ),
        migrations.AlterField(
            model_name='coremeasurerelateddata',
            name='data_viz_type',
            field=models.CharField(choices=[(b'pie', b'Pie Chart'), (b'bar', b'Bar Chart'), (b'link', b'Link'), (b'list', b'List'), (b'map', b'Map'), (b'number', b'Big Number')], default=b'', help_text=b'Select the type of data vizulation for this Core Measure', max_length=1, null=True, verbose_name=b'Data Viz Type'),
        ),
        migrations.AlterField(
            model_name='coremeasurerelateddata',
            name='prime_label',
            field=models.TextField(blank=True, default=b'', help_text=b'This will be primary label/text for the data visualization', null=True, verbose_name=b'Prime Label'),
        ),
        migrations.AlterField(
            model_name='coremeasurerelateddata',
            name='x_axis_label',
            field=models.CharField(blank=True, default=b'', help_text=b'Enter your x-axis label here', max_length=255, null=True, verbose_name=b'X-Axis Label'),
        ),
        migrations.AlterField(
            model_name='coremeasurerelateddata',
            name='y_axis_label',
            field=models.CharField(blank=True, default=b'', help_text=b'Enter your y-axis label here', max_length=255, null=True, verbose_name=b'Y-Axis Label'),
        ),
        migrations.AlterField(
            model_name='coremeasurerelateddata',
            name='year',
            field=models.CharField(blank=True, default=b'', help_text=b'Input the year/date range for the associated data visualization', max_length=255, null=True),
        ),
    ]
