# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 17:27
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0009_auto_20160413_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coremeasure',
            name='body_content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=None, null=True, verbose_name=b'Extra Content'),
        ),
    ]
