# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0010_auto_20160414_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coremeasurerelateddata',
            name='data_viz_type',
            field=models.CharField(choices=[(b'pie', b'Pie Chart'), (b'bar', b'Bar Chart'), (b'link', b'Link'), (b'list', b'List'), (b'map', b'Map'), (b'number', b'Big Number')], default=None, help_text=b'Select the type of data vizulation for this Core Measure', max_length=10, null=True, verbose_name=b'Data Viz Type'),
        ),
    ]
