# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0011_auto_20160415_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coremeasurerelateddata',
            name='data_viz_type',
            field=models.CharField(choices=[(b'pie', b'Pie Chart'), (b'bar', b'Bar Chart'), (b'link', b'Yes! Link'), (b'map', b'District Map'), (b'number', b'Big Number')], default=None, help_text=b'Select the type of data vizulation for this Core Measure', max_length=10, null=True, verbose_name=b'Data Viz Type'),
        ),
    ]
