# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-30 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0012_auto_20160426_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremeasure',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
