# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0013_coremeasure_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coremeasurerelateddata',
            name='prime_label',
        ),
        migrations.RemoveField(
            model_name='coremeasurerelateddata',
            name='x_axis_label',
        ),
        migrations.RemoveField(
            model_name='coremeasurerelateddata',
            name='y_axis_label',
        ),
        migrations.AlterField(
            model_name='coremeasurerelateddata',
            name='data_values',
            field=models.TextField(blank=True, default=b'', help_text=b'Enter your values here. If there is more than one value present, separate them by a semicolon', null=True, verbose_name=b'Data'),
        ),
    ]
