# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0014_auto_20160504_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremeasurerelateddata',
            name='prime_label',
            field=models.TextField(blank=True, default=b'', help_text=b'This will be primary label/text for the data visualization', null=True, verbose_name=b'Prime Label'),
        ),
    ]
