# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0015_coremeasurerelateddata_prime_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coremeasurerelateddata',
            name='data_labels',
            field=models.CharField(blank=True, default=b'', help_text=b'Enter your labels here. If there is more than one label present, separate them by a semicolon. Please limit your labels to approx. 30 characters.', max_length=255, null=True, verbose_name=b'Data Labels'),
        ),
    ]
